
dataset:
  path: /home/guy/Projects/Traffic/traffic_data_pt
  labels_path: /home/guy/Projects/Traffic/Traffic-DSTG-Gen/eda_exports
  batch_size: 32
  shuffle: false
  preserve_temporal_order: true
  num_workers: 8
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

model:
  name: baseline_gcn
  node_in_channels: 22
  hidden_channels: 64
  out_channels: 1
  dropout: 0.3

training:
  epochs: 100
  lr: 0.0005
  eval_interval: 1