
dataset:
  path: /home/guy/Projects/Traffic/traffic_data_pt
  batch_size: 32
  shuffle: true
  num_workers: 8

model:
  name: baseline_gcn
  in_channels: 22
  hidden_channels: 64
  out_channels: 1
  dropout: 0.3

training:
  epochs: 100
  lr: 0.001